Testing, more tests, fixes, coverage analysis.

diff --git a/system-test b/system-test
--- a/system-test
+++ b/system-test
@@ -20,6 +20,7 @@ fi
 HOSTNAME=$(hostname)
 PORT=8888
 NUM="$1"
+PROJECTDIR=$(pwd)
 PREFIX="/tmp/htcache-systemtest$NUM"
 LOG_LEVEL=7
 ERR_LEVEL=7
@@ -39,7 +40,6 @@ WAIT=1.5
 
 function clean
 {
-    [ -e .coverage ] && rm .coverage
     test -e $PID && kill -int `cat $PID`
     rm -rf $PREFIX*
 }
@@ -69,6 +69,20 @@ function startserver
   fi
 }
 
+function stopserver
+{
+  if test -e $PID
+  then
+    if kill -int `cat $PID`
+    then
+        echo "Interrupted server at $(cat $PID)"
+    else
+        echo "Error closing server normally"
+    fi
+    rm $PID
+  fi
+}
+
 function htcache_command
 {
   htcache \
@@ -77,6 +91,19 @@ function htcache_command
     --daemon $PREFIX.log \
     $*
 } 
+
+function abort
+{
+  sleep $1
+  if kill %%
+  then
+    echo
+    sleep 1
+  else
+    echo "ERROR: download finished unexpectedly soon"
+    exit 1
+  fi
+}
 
 function sortheaders
 {
@@ -161,7 +188,8 @@ if which curl > /dev/null; then
       echo "Resuming unfinished download at $(stat -c "%s" $PREFIX.$2) bytes"
       CURLARGS="-C - "
     fi
-    curl $CURLARGS -s -S -o $PREFIX.$2 --dump-header $PREFIX.$2.headers $1  1>&2
+    curl $CURLARGS -s -S -o $PREFIX.$2 --dump-header $PREFIX.$2.headers $1 \
+        -H "X-HTCache-Unittest: $1 $2" $3 1>&2
     echo "Finished file download at $(stat -c "%s" $PREFIX.$2) bytes"
     splitheaders $2
   }
@@ -169,19 +197,6 @@ else
   echo "ERROR: no download tool available, install curl"
   exit 1
 fi
-
-function abort
-{
-  sleep $1
-  if kill %%
-  then
-    echo
-    sleep 1
-  else
-    echo "ERROR: download finished unexpectedly soon"
-    exit 1
-  fi
-}
 
 function touchfile
 {
@@ -239,17 +254,19 @@ fi
 
 function check_equal
 {
-  if test ! -e $PREFIX.$2; then
+    [ "${2:0:1}" = "/" ] && F1=$2 || F1=$PREFIX.$2
+    [ "${3:0:1}" = "/" ] && F2=$3 || F2=$PREFIX.$3
+  if test ! -e $F1; then
     check "$1" ERROR "1st missing:" 
     echo "-> $2"
-  elif test ! -e $PREFIX.$3; then
+  elif test ! -e $F2; then
     check "$1" ERROR "2nd missing:"
     echo "-> $3"
-  elif test `checksum $PREFIX.$2` != `checksum $PREFIX.$3`; then
+  elif test `checksum $F1` != `checksum $F2`; then
     if test -n "$4";
     then
       check "$1" ERROR "not equal:"
-      comm -3 $PREFIX.$2 $PREFIX.$3
+      comm -3 $F1 $F2
     else
       check "$1" ERROR "not equal"
     fi
@@ -290,18 +307,9 @@ function check_headers
   fi
 }
 
-function stopserver
+function backup_coverage
 {
-  if test -e $PID
-  then
-    if kill -int `cat $PID`
-    then
-        echo "Interrupted server at $(cat $PID)"
-    else
-        echo "Error closing server normally"
-    fi
-    rm $PID
-  fi
+  cp .coverage .coverage-$1
 }
 
 function coveragereport
@@ -310,6 +318,7 @@ function coveragereport
   echo Generating coverage report
   coverage combine
   coverage html
+  coverage report
 }
 
 ########## UNIT TESTS #########################################################
@@ -325,6 +334,7 @@ case $1 in
     download http://$URL_HTTP out1
     http_proxy=$HOSTNAME:$PORT download http://$URL_HTTP out2
     stopserver
+    backup_coverage $1
 
     check_exists "file cached and finalized" cache/$URL_HTTP
     check_url_cached "record exists" http://$URL_HTTP
@@ -345,6 +355,7 @@ case $1 in
     ( ( http_proxy=$HOSTNAME:$PORT download http://$URL_HTTP cached & abort $ABORT; splitheaders cached ) & )
     sleep $WAIT
     stopserver
+    backup_coverage $1
 
     check_log "aborted client read" "Client aborted"
     check_url_cached "record exists" http://$URL_HTTP
@@ -373,6 +384,7 @@ case $1 in
     sleep 4
     http_proxy=$HOSTNAME:$PORT download http://$URL_HTTP out2
     stopserver
+    backup_coverage $1
     
     check_exists "first file cached and finalized" cache/$URL_HTTP
     check_url_cached "record exists" http://$URL_HTTP
@@ -401,6 +413,7 @@ case $1 in
     http_proxy=$HOSTNAME:$PORT download http://$URL_HTTP out2
     sleep $WAIT
     stopserver
+    backup_coverage $1
 
     check_log "received complete file" "Server responds 'HTTP/1.1 200 OK'"
     check_log "served partial file" "HTCache responds 'HTTP/1.1 206 Partial Content'"
@@ -437,6 +450,7 @@ case $1 in
     http_proxy=$HOSTNAME:$PORT download http://$URL_HTTP out2
     sleep 0.5
     stopserver
+    backup_coverage $1
 
     check_equal "cached and served file are equal" cache/$URL_HTTP out2
     check_log "htcache asks for missing part" "Requesting resume of partial file in cache"
@@ -476,6 +490,7 @@ case $1 in
     http_proxy=$HOSTNAME:$PORT download http://$URL_HTTP out5
     sleep 0.5
     stopserver
+    backup_coverage $1
 
     check_equal "cache and normal download are equal" cache/$URL_HTTP out
     check_log "downloads are joined" "Joining running download"
@@ -498,6 +513,7 @@ case $1 in
     http_proxy=$HOSTNAME:$PORT download http://$URL_CHUNKED out2
     sleep 0.5
     stopserver
+    backup_coverage $1
 
     check_equal "separate download and served file are equal" out1 out2
     check_log "server sends chunked data" "Transfer-Encoding: chunked"
@@ -515,6 +531,7 @@ case $1 in
     startserver --drop $PREFIX-rules.drop
     http_proxy=$HOSTNAME:$PORT download http://$URL_HTTP out
     stopserver
+    backup_coverage $1
     
     check_log "blocked request to server" "Switching to BlockedContentResponse"
     check_headers out "server sent 403" "HTTP/1.1 403 Dropped By Proxy"
@@ -530,6 +547,7 @@ case $1 in
     startserver --nocache $PREFIX-rules.nocache
     http_proxy=$HOSTNAME:$PORT download http://$URL_HTTP out
     stopserver
+    backup_coverage $1
     check_log "blocked request to server" "Switching to BlindResponse"
     check_headers out "served HTTP v1.* OK" "HTTP/1.* 200 "
     check_log_errors
@@ -543,6 +561,7 @@ case $1 in
     download ftp://$URL_FTP out1
     ftp_proxy=$HOSTNAME:$PORT download ftp://$URL_FTP out2
     stopserver
+    backup_coverage $1
 
     check_equal "separate download and served file are equal" out1 out2
     check_equal "cached and served file are equal" cache/$URL_FTP out2
@@ -557,6 +576,7 @@ case $1 in
     ftp_proxy=$HOSTNAME:$PORT download ftp://$URL_FTP out1
     ftp_proxy=$HOSTNAME:$PORT download ftp://$URL_FTP out2
     stopserver
+    backup_coverage $1
 
     check_exists "first file cached and finalized" cache/$URL_FTP
     check_log "second file served from cache" "Reading complete file from cache"
@@ -573,6 +593,7 @@ case $1 in
     ( ( ftp_proxy=$HOSTNAME:$PORT download ftp://$URL_FTP out1 & abort $ABORT ) & )
     ftp_proxy=$HOSTNAME:$PORT download ftp://$URL_FTP out2
     stopserver
+    backup_coverage $1
 
     check_log "htcache resumes file" "Resuming partial file in cache"
     check_equal "cached and served file are equal" cache/$URL_FTP out2
@@ -598,6 +619,7 @@ case $1 in
     http_proxy=$HOSTNAME:$PORT download http://$URL_HTTP out1
     http_proxy=$HOSTNAME:$PORT download http://$URL_HTTP out2
     stopserver
+    backup_coverage $1
 
     check_log "serving directly from cache without consulting server" "Static mode; serving file directly from cache"
     check_equal "cached and served file are equal" cache/$URL_HTTP out2
@@ -611,6 +633,7 @@ case $1 in
     startserver --offline
     http_proxy=$HOSTNAME:$PORT download http://$URL_HTTP out
     stopserver
+    backup_coverage $1
 
     check_log "refusing to connect to server" "AssertionError: operating in off-line mode"
     check_log_errors
@@ -621,16 +644,69 @@ case $1 in
 
     clean
     startserver
+    http_proxy=$HOSTNAME:$PORT download http://dotmpe.com/ out1
+    # DNS exception:
+    http_proxy=$HOSTNAME:$PORT download http://sdfsdfegsdv.jill/ out2
+    # Moved Permanently
+    http_proxy=$HOSTNAME:$PORT download http://nu.nl/ out3
+    # Forbidden
+    http_proxy=$HOSTNAME:$PORT download http://dotmpe.com/.htaccess out4
+    # Not found
+    http_proxy=$HOSTNAME:$PORT download http://dotmpe.com/test/404 out5
+    # TODO: Gone
+    #http_proxy=$HOSTNAME:$PORT download http://dotmpe.com/test/old out7
+    # TODO: TCN
+# TODO: fix these requests:
     http_proxy=$HOSTNAME:$PORT download \
-          http://jeelabs.net/projects/hardware/wiki/AA_Power_Board out1
-    http_proxy=$HOSTNAME:$PORT download \
-          http://jethomson.wordpress.com/2011/08/18/project-ouroboros-reflashing-a-betemcu-usbasp-programmer/ out2
+          http://jethomson.wordpress.com/2011/08/18/project-ouroboros-reflashing-a-betemcu-usbasp-programmer/ out6
+    http_proxy=$HOSTNAME:$PORT download http://jeelabs.net/projects/hardware/wiki/AA_Power_Board out7
+#    http_proxy=$HOSTNAME:$PORT telnet $HOSTNAME $PORT < tmp
     stopserver
-
+    backup_coverage $1
+    check_log "DNS exception" "DNSLookupException"
+    check_log "Moved Permanently" "Server responds 'HTTP/1.1 301 Moved Permanently'"
+    check_log "Forbidden" "Server responds 'HTTP/1.1 403 Forbidden'"
+    check_log "Not Found" "Server responds 'HTTP/1.1 404 Not Found'"
     check_log_errors
     ;;
 
   19)
+    summary "HTTP POST"
+    clean
+    startserver
+    http_proxy=$HOSTNAME:$PORT download http://dotmpe.com/ out2 "-X POST -F debug=1"
+    sleep 2
+    stopserver
+    backup_coverage $1
+    check_log_errors
+    ;;
+
+  20)
+    summary "DIRECT REQUEST"
+    clean
+    startserver
+    http_proxy=$HOSTNAME:$PORT download http://$HOSTNAME:$PORT/info info
+    http_proxy=$HOSTNAME:$PORT download http://$HOSTNAME:$PORT/downloads downloads
+    http_proxy=$HOSTNAME:$PORT download http://$HOSTNAME:$PORT/list list
+    http_proxy=$HOSTNAME:$PORT download http://$HOSTNAME:$PORT/echo echo
+    http_proxy=$HOSTNAME:$PORT download http://$URL_HTTP out
+    http_proxy=$HOSTNAME:$PORT download http://$HOSTNAME:$PORT/page-info page-info "-F url=http://$URL_HTTP" 
+    http_proxy=$HOSTNAME:$PORT download http://$HOSTNAME:$PORT/dhtml.css dhtml.css
+    http_proxy=$HOSTNAME:$PORT download http://$HOSTNAME:$PORT/dhtml.js dhtml.js
+    stopserver
+    backup_coverage $1
+    check_equal "dhtml.css" dhtml.css $PROJECTDIR/dhtml.css
+    check_equal "dhtml.js" dhtml.js $PROJECTDIR/dhtml.js
+    check_log_errors
+    ;;
+
+  21)
+    summary "SERVICE"
+    # XXX: htcache_command
+    ;;
+
+  22)
+    summary "COVERAGE REPORT"
     coveragereport
     ;;
 
