Unittests, header checks (now 35 checks, 8 errors).
- Now serving 403 for filtered content. Added unit test.
- Expanded unit-test script to check aspects of headers.
  Now testing for the equality of the entity headers.

diff --git a/unit-test b/unit-test
--- a/unit-test
+++ b/unit-test
@@ -1,7 +1,7 @@
 #! /bin/bash
 # 
 # Unit tests originally for http-replicator, 
-# adapted for htcache. Public domain?
+# adapted for htcache. Public domain.
 # 
 
 PORT=8090
@@ -30,49 +30,89 @@ function startserver
     cat $PID
     rm $PID
     exit 1
+  else
+    echo Started server 
   fi
 }
 
-function stripheaders
+function sortheaders
 {
-    mv $1 $1.tmp
-    HEADERS_RECEIVED=
-    while read L < $1.tmp
-    do
-        if [ -z "$()" ]; then
-            HEADERS_RECEIVED=1
-        fi
-        if [ -n "$HEADERS_RECEIVED" ]; then
-            echo $L | grep -v '^\(HTTP\|Connection\|Accept-\|P3P\|Via\|X-\|Date\)'
-        else
-            echo $L > $1
-        fi
-    done
+    tail -n +2 $1 > $1.tmp
+    statusline=$(head -n 1 $1)
+    echo $statusline > $1
+    sort $1.tmp >> $1
+    rm $1.tmp
 }
 
-if which wget > /dev/null; then
-  function download
-  {
-    if test -e $PREFIX.$2; then
-      WGETARGS="-c"
+# XXX: if dumping headers, some script needs to make sure only entity
+# headers are saved. Non-entity headers must be tested for  --save-headers  
+function splitheaders
+{
+    echo Splitting header $2
+    for f in $PREFIX.$1.entity.headers $PREFIX.$1.headers;
+    do [ -e "$f" ] && rm $f; done
+    mv $PREFIX.$1 $PREFIX.tmp
+    ENVELOPE=$(head -n 1 $PREFIX.tmp)
+    HEADERS_RECEIVED=$([ "${ENVELOPE:0:8}" = "HTTP/1.1" ] && echo 0 || echo 1)
+    LINE=0
+    if [ $HEADERS_RECEIVED = 0 ]
+    then
+        while read L
+        do
+            LINE=$(($LINE + 1))
+            if [ $LINE = 1 ]
+            then
+                # dot not want to compare statusline b/c protocol version
+                echo $L > $PREFIX.$1.headers
+                continue
+            fi
+            if [ "$L" = "$(printf '\r\n')" ]; then
+                break
+            fi
+            STRIP=$(echo $L | grep -v '^\(Connection\|Accept-\|P3P\|Via\|X-\|Cache-\|Date\|Expires\)')
+            if [ -n "$STRIP" ]
+            then
+                # Keep entity headers for comparison
+                echo $L >> $PREFIX.$1.entity.headers
+            fi
+            # Keep all headers for other checks
+            echo $L >> $PREFIX.$1.headers
+        done < $PREFIX.tmp
     fi
-    # XXX: if dumping headers, some script needs to make sure only entity
-    # headers are saved. Non-entity headers must be tested for  --save-headers  
-    wget -q -O $PREFIX.$2 $1 $WGETARGS 1>&2
-    #stripheaders $PREFIX.$2
-  }
-elif which curl > /dev/null; then
+    LINE=$(($LINE + 1))
+    tail -n +$LINE $PREFIX.tmp > $PREFIX.$1
+
+    sortheaders $PREFIX.$1.headers
+    sortheaders $PREFIX.$1.entity.headers
+
+    [ -e $PREFIX.tmp ] && rm $PREFIX.tmp
+}
+
+# XXX: could not figure out a way to make wget save for non 200
+#if which wget > /dev/null; then
+#  function download
+#  {
+#    echo Downloading $2 $1
+#    if test -e $PREFIX.$2; then
+#      WGETARGS="-c"
+#    fi
+#    wget --save-headers -O $PREFIX.$2 $1 $WGETARGS
+#    #1>&2
+#    splitheaders $2
+#  }
+#el
+if which curl > /dev/null; then
   function download
   {
+    echo Downloading $2 $1
     if test -e $PREFIX.$2; then
       CURLARGS="-C -"
     fi
-    curl -o $PREFIX.$2 $CURLARGS $1 1>&2
-    #-D  
-    #stripheaders $PREFIX.$1
+    curl -s -S -i -o $PREFIX.$2 $CURLARGS $1 1>&2
+    splitheaders $2
   }
 else
-  echo "error: no download tool available"
+  echo "error: no download tool available, install curl"
   exit 1
 fi
 
@@ -155,6 +195,15 @@ function check_log
   fi
 }
 
+function check_headers
+{
+  if grep -q "$3" $PREFIX.$1.headers; then
+    check "$2" OK
+  else
+    check "$2" ERROR
+  fi
+}
+
 function stopserver
 {
   #echo "============================================================================="
@@ -186,24 +235,35 @@ case $1 in
     check_exists "file cached and finalized" cache/$URL_HTTP
     check_equal "separate download and served file are equal" out1 out2
     check_equal "cached and served file are equal" cache/$URL_HTTP out2
+    check_equal "normal and served entity headers are equal" out1.entity.headers out2.entity.headers
+    check_headers out2 "served HTTP v1.1 OK" "HTTP/1.1 200 "
+    check_headers out2 "served via proxy" "Via:\ [a-z\.-]\+:$PORT\s*$"
     stopserver
     ;;
   2)
     startserver
-    http_proxy=localhost:$PORT download http://$URL_HTTP out & abort 1
+    download http://$URL_HTTP normal
+    http_proxy=localhost:$PORT download http://$URL_HTTP cached & abort 1
     summary "LEAVING PARTIAL FILE IN CACHE"
     check_exists "file cached, not finalized" cache/$URL_HTTP.incomplete
+    check_equal "headers are equal" normal.entity.headers cached.entity.headers
+    check_headers cached "served HTTP v1.1 OK" "HTTP/1.1 200 "
     stopserver
     ;;
   3)
     startserver
+    download http://$URL_HTTP out
     http_proxy=localhost:$PORT download http://$URL_HTTP out1
     http_proxy=localhost:$PORT download http://$URL_HTTP out2
     summary "SERVING FILE FROM CACHE"
     check_exists "first file cached and finalized" cache/$URL_HTTP
+    check_headers out1 "served HTTP v1.1 OK" "HTTP/1.1 200 "
     check_log "second file served from cache" "Reading complete file from cache"
+    check_headers out2 "served HTTP v1.1 OK" "HTTP/1.1 200 "
     check_equal "cached and first served file are equal" cache/$URL_HTTP out1
     check_equal "cached and second served file are equal" cache/$URL_HTTP out2
+    check_equal "normal and first served headers are equal" out.entity.headers out1.entity.headers
+    check_equal "normal and second served headers are equal" out.entity.headers out2.entity.headers
     stopserver
     ;;
   4)
@@ -213,6 +273,7 @@ case $1 in
     summary "RESUMING PARTIAL FILE BY CLIENT"
     check_log "received complete file" "Server responds HTTP/1.1 200 OK"
     check_log "served partial file" "HTCache responds HTTP/1.1 206 Partial Content"
+    check_headers out "served HTTP v1.1 OK" "HTTP/1.1 200 "
     check_equal "cached and served file are equal" cache/$URL_HTTP out
     stopserver
     ;;
@@ -224,6 +285,7 @@ case $1 in
     check_log "detected complete file in cache" "Checking complete file in cache"
     check_log "downloading new file" "Preparing new file in cache"
     check_equal "cached and served file are equal" cache/$URL_HTTP out
+    check_headers out "served HTTP v1.1 OK" "HTTP/1.1 200 "
     stopserver
     ;;
   6)
@@ -267,6 +329,35 @@ case $1 in
     check_equal "cached and served file are equal" cache/$URL_CHUNKED out2
     stopserver
     ;;
+  10)
+    echo "[^/]*w3\.org\/Protocols\/HTTP.*" > $PREFIX-rules.drop
+    startserver --drop $PREFIX-rules.drop
+    http_proxy=localhost:$PORT download http://$URL_HTTP out
+    summary "FILTERED PROXY RESPONSE"
+    check_log "blocked request to server" "Switching to BlockedContentResponse"
+    check_headers out "server sent 403" "HTTP/1.1 403 Dropped By Proxy"
+    check_headers out.entity "served HTML" "Content-Type: text\/html"
+    stopserver
+    rm $PREFIX-rules.drop
+    ;;
+#  10)
+#    startserver --join rules.join
+#    http_proxy=localhost:$PORT download http://$URL_HTTP out
+#    summary "JOINED PROXY RESPONSE"
+#    stopserver
+#    ;;
+  11)
+    startserver --nocache rules.nocache
+    http_proxy=localhost:$PORT download http://$URL_HTTP out
+    summary "BLIND PROXY RESPONSE"
+    stopserver
+    ;;
+#  12)
+#    startserver --proc rules.proc
+#    http_proxy=localhost:$PORT download http://$URL_HTTP out
+#    summary "POST-PROCESSED PROXY RESPONSE"
+#    stopserver
+#    ;;
 #  10)
 #    startserver
 #    download ftp://$URL_FTP out1
@@ -321,7 +412,7 @@ case $1 in
 #    stopserver
 #    ;;
 
-  10)
+  11)
     coveragereport
     ;;
 
